apiVersion: v1
kind: Service
metadata:
  name: spark-master-external
  namespace: spark-hadoop
spec:
  selector:
    app: spark-master
  ports:
  - name: yarn-ui
    port: 8088
    targetPort: 8088
    nodePort: 30088
  - name: spark-master-ui
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: namenode-ui
    port: 9870
    targetPort: 9870
    nodePort: 30870
  - name: jupyter
    port: 8888
    targetPort: 8888
    nodePort: 30888
  - name: nodemanager
    port: 8042
    targetPort: 8042
    nodePort: 30042
  - name: fastapi
    port: 8000
    targetPort: 8000
    nodePort: 30000
  - name: spark-app
    port: 4040
    targetPort: 4040
    nodePort: 30040
  - name: spark-history
    port: 18080
    targetPort: 18080
    nodePort: 31080
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-1-external
  namespace: spark-hadoop
spec:
  selector:
    app: spark-worker-1
  ports:
  - name: worker-ui
    port: 8081
    targetPort: 8081
    nodePort: 30081
  - name: nodemanager
    port: 8042
    targetPort: 8042
    nodePort: 30642
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-2-external
  namespace: spark-hadoop
spec:
  selector:
    app: spark-worker-2
  ports:
  - name: worker-ui
    port: 8081
    targetPort: 8081
    nodePort: 30082
  - name: nodemanager
    port: 8042
    targetPort: 8042
    nodePort: 30742
  type: NodePort