apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ubuntu_user/cluster-hadoop/user_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-data-pvc
  namespace: spark-hadoop
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi