apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-1
  namespace: spark-hadoop
  labels:
    app: spark-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-1
  template:
    metadata:
      labels:
        app: spark-worker-1
    spec:
      hostname: spark-worker-1
      containers:
      - name: spark-worker
        image: raulcsouza/spark-worker-hadoop
        imagePullPolicy: IfNotPresent
        tty: true
        ports:
        - containerPort: 8081
          name: worker-ui
        - containerPort: 8042
          name: nodemanager
        env:
        - name: SPARK_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-1-service
  namespace: spark-hadoop
spec:
  selector:
    app: spark-worker-1
  ports:
  - name: worker-ui
    port: 8081
    targetPort: 8081
  - name: nodemanager
    port: 6042
    targetPort: 8042
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker-2
  namespace: spark-hadoop
  labels:
    app: spark-worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-worker-2
  template:
    metadata:
      labels:
        app: spark-worker-2
    spec:
      hostname: spark-worker-2
      containers:
      - name: spark-worker
        image: raulcsouza/spark-worker-hadoop
        imagePullPolicy: IfNotPresent
        tty: true
        ports:
        - containerPort: 8081
          name: worker-ui
        - containerPort: 8042
          name: nodemanager
        env:
        - name: SPARK_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: SPARK_MASTER
          value: "spark://spark-master:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-2-service
  namespace: spark-hadoop
spec:
  selector:
    app: spark-worker-2
  ports:
  - name: worker-ui
    port: 8082
    targetPort: 8081
  - name: nodemanager
    port: 7042
    targetPort: 8042
  type: ClusterIP