apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: spark-worker
  name: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: spark-worker
  template:
    metadata:
      labels:
        io.kompose.service: spark-worker
    spec:
      containers:
        - image: spark-worker-hadoop:latest
          imagePullPolicy: Never
          name: spark-worker
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8042
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /tmp/hadoop-root/dfs/data
              name: hdfs-datanode-storage
      restartPolicy: Always
      volumes:
        - name: hdfs-datanode-storage
          persistentVolumeClaim:
            claimName: hdfs-datanode-pvc