apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9870"
      port: 9870
      targetPort: 9870
    - name: "8888"
      port: 8888
      targetPort: 8888
    - name: "8042"
      port: 8042
      targetPort: 8042
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "4040"
      port: 4040
      targetPort: 4040
    - name: "18080"
      port: 18080
      targetPort: 18080
  selector:
    io.kompose.service: spark-master
