apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: spark-worker
  name: spark-worker
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "8042"
      port: 8042
      targetPort: 8042
  selector:
    io.kompose.service: spark-worker