apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-worker-2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --out k8s/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: spark-worker-2
    spec:
      containers:
        - env:
            - name: SPARK_LOCAL_IP
              value: 10.5.0.4
          image: raulcsouza/spark-worker-hadoop
          name: spark-worker-2
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8042
              protocol: TCP
          tty: true
      hostname: spark-worker-2
      restartPolicy: Always
