apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out k8s/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: spark-worker-2
  name: spark-worker-2
spec:
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8081
    - name: "7042"
      port: 7042
      targetPort: 8042
  selector:
    io.kompose.service: spark-worker-2
